return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	opts = {
		ensure_installed = {
			"lua",
			"javascript",
			"typescript",
			"go",
			"python",
			"java",
			"html",
			"css",
			"json",
			"tsx",
			"c",
			"vim",
			"vimdoc",
			"rust",
			"markdown",
			"yaml",
			"bash",
			"dockerfile",
			"gitignore",
			"toml",
		},
		sync_install = false,
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
		indent = { enable = true },
	},
}
